on:
  workflow_dispatch:

name: sanitizers

permissions:
  contents: read

jobs:
  sanitizers:
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
      CXXFLAGS: "-fsanitize=undefined"
      LINK: clang++
      ASAN: true
      UBSAN: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/jammy/latest
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      ## R CMD check
      _R_CHECK_CRAN_INCOMING_: false
      _R_CHECK_LENGTH_1_CONDITION_: true
      _R_CHECK_LENGTH_1_LOGIC2_: true
      _R_CHECK_MATRIX_DATA_: true
      ## Specific to package
      _R_CHECK_USE_VALGRIND_: true
      UBSAN_OPTIONS: "print_stacktrace=1"
          