# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create the sparse triangular matrix U for multivariate Vecchia models
#'
#' This creates the sparse triangular matrix U for multivariate Vecchia
#' models. This matrix can be used to estimate the likelihood or transform
#' the data to be iid. This function is a multivariate version of
#' \code{\link[GPvecchia]{createU}}.
#'
#' @param vec_approx Object returned by \code{\link{vecchia_Mspecify}}.
#' @param params Vector of covariance parameters. See
#' \code{\link{create_param_sequence}} or the examples below for details
#' about the format of this vector.
#'
#' @return A list containing the sparse upper trianguler U, plus additional
#' objects required for other functions.
#'
#' @seealso \code{\link[GPvecchia]{createU}}, \code{\link{vecchia_Mspecify}},
#' \code{\link{create_param_sequence}}
#'
#' @references
#' \itemize{
#' \item Apanasovich, T.V., Genton, M.G. and Sun, Y. "A valid Matérn class of
#' cross-covariance functions for multivariate random fields with any number
#' of components", Journal of the American Statistical Association (2012)
#' 107(497):180-193.
#' \item Katzfuss, M., and Guinness, J. "A general framework for Vecchia
#' approximations of Gaussian processes", Statistical Science (2021)
#' 36(1):124-141.
#' }
#'
#' @export
#' @examples
#' data(soil)
#' soil <- soil[!is.na(soil[,5]),] # remove rows with NA's
#' locs <- as.matrix(soil[,1:2])
#' locsm <- list()
#' locsm[[1]] <- locsm[[2]] <- locs
#' soil.va <- vecchia_Mspecify(locsm, m=10)
#'
#' pseq <- create_param_sequence(2)
#' # Initialize the vector of covariance parameters
#' params <- rep(NA, pseq[5,2])
#' # Sigma parameters:
#' params[pseq[1,1]:pseq[1,2]] <- c(100, 80)
#' # Scale parameters:
#' params[pseq[2,1]:pseq[2,2]] <- c(60, 50)
#' # Smoothness parameters:
#' params[pseq[3,1]:pseq[3,2]] <- c(0.5, 0.5)
#' # Nuggets:
#' params[pseq[4,1]:pseq[4,2]] <- c(30, 30)
#' # Correlation:
#' params[pseq[5,1]:pseq[5,2]] <- -0.9
#'
#' soil.u <- createUMultivariate(soil.va, params)
createUMultivariate <- function(vec_approx, params) {
    .Call('_PrestoGP_createUMultivariate', PACKAGE = 'PrestoGP', vec_approx, params)
}

MMatern_cov <- function(locs, y_ndx, covparams, P) {
    .Call('_PrestoGP_MMatern_cov', PACKAGE = 'PrestoGP', locs, y_ndx, covparams, P)
}

unlog_params <- function(logparams, param_seq, P) {
    .Call('_PrestoGP_unlog_params', PACKAGE = 'PrestoGP', logparams, param_seq, P)
}

vecchia_likelihood_U_cpp <- function(z, U_obj) {
    .Call('_PrestoGP_vecchia_likelihood_U_cpp', PACKAGE = 'PrestoGP', z, U_obj)
}

#' Evaluation of the multivariate Vecchia likelihood
#'
#' This function is used to evaluate the multivariate Vecchia likelihood.
#'
#' @param z The observed data.
#' @param vecchia_approx A Vecchia object returned by
#' \code{\link{vecchia_Mspecify}}.
#' @param covparams Vector of covariance parameters. See
#' \code{\link{create_param_sequence}} or the examples below for details
#' about the format of this vector.
#'
#' @return The log likelihood implied by the multivariate Vecchia
#' approximation.
#'
#' @seealso \code{\link[GPvecchia]{vecchia_likelihood}},
#' \code{\link{vecchia_Mspecify}}, \code{\link{create_param_sequence}}
#'
#' @references
#' \itemize{
#' \item Katzfuss, M., and Guinness, J. "A general framework for Vecchia
#' approximations of Gaussian processes", Statistical Science (2021)
#' 36(1):124-141.
#' }
#'
#' @export
#' @examples
#' data(soil)
#' soil <- soil[!is.na(soil[,5]),] # remove rows with NA's
#' locs <- as.matrix(soil[,1:2])
#' locsm <- list()
#' locsm[[1]] <- locsm[[2]] <- locs
#' soil.va <- vecchia_Mspecify(locsm, m=10)
#'
#' pseq <- create_param_sequence(2)
#' # Initialize the vector of covariance parameters
#' params <- rep(NA, pseq[5,2])
#' # Sigma parameters:
#' params[pseq[1,1]:pseq[1,2]] <- c(100, 80)
#' # Scale parameters:
#' params[pseq[2,1]:pseq[2,2]] <- c(60, 50)
#' # Smoothness parameters:
#' params[pseq[3,1]:pseq[3,2]] <- c(0.5, 0.5)
#' # Nuggets:
#' params[pseq[4,1]:pseq[4,2]] <- c(30, 30)
#' # Correlation:
#' params[pseq[5,1]:pseq[5,2]] <- -0.9
#'
#' vecchia_Mlikelihood(rnorm(nrow(locs)), soil.va, params)
vecchia_Mlikelihood <- function(z, vecchia_approx, covparams) {
    .Call('_PrestoGP_vecchia_Mlikelihood', PACKAGE = 'PrestoGP', z, vecchia_approx, covparams)
}

mvnegloglik <- function(logparams, vecchia_approx, y, param_seq, P) {
    .Call('_PrestoGP_mvnegloglik', PACKAGE = 'PrestoGP', logparams, vecchia_approx, y, param_seq, P)
}

mvnegloglik_ST <- function(logparams, vecchia_approx, y, param_seq, P, scaling, nscale) {
    .Call('_PrestoGP_mvnegloglik_ST', PACKAGE = 'PrestoGP', logparams, vecchia_approx, y, param_seq, P, scaling, nscale)
}

#' Extract specific Matern parameters from a parameter sequence
#'
#' This function is used to obtain specific Matern parameters (e.g.,
#' range or smoothness) from the covparams slot of a PrestoGPModel object.
#'
#' @param P Number of outcome variables
#' @param ns Number of scale parameters
#'
#' @details This function is intended for advanced users who want to specify
#' the input Matern parameters for functions such as
#' \code{\link{vecchia_Mlikelihood}} or \code{\link{createUMultivariate}}.
#' To extract the Matern parameters from a fitted PrestoGP model, it is
#' strongly recommended to use \code{link{get_theta}} instead.
#'
#' @return A matrix with five rows and two columns as described below:
#' \describe{
#' \item{Row 1:}{Starting and ending indices for the sigma parameter(s)}
#' \item{Row 2:}{Starting and ending indices for the scale parameter(s)}
#' \item{Row 3:}{Starting and ending indices for the smoothness parameter(s)}
#' \item{Row 4:}{Starting and ending indices for the nugget(s)}
#' \item{Row 5:}{Starting and ending indices for the correlation parameter(s)}
#' }
#'
#' @seealso \code{\link{PrestoGPModel-class}}
#'
#' @references
#' \itemize{
#' \item Apanasovich, T.V., Genton, M.G. and Sun, Y. "A valid Matérn class of
#' cross-covariance functions for multivariate random fields with any number
#' of components", Journal of the American Statistical Association (2012)
#' 107(497):180-193.
#' \item Genton, M.G. "Classes of kernels for machine learning: a statistics
#' perspective", The Journal of Machine Learning Research (2001) 2:299-312.
#' }
#'
#' @export
#' @examples
#' # Space/elevation model
#' data(soil250, package="geoR")
#' y2 <- soil250[,7]               # predict pH level
#' X2 <- as.matrix(soil250[,c(4:6,8:22)])
#' # columns 1+2 are location coordinates; column 3 is elevation
#' locs2 <- as.matrix(soil250[,1:3])
#'
#' soil.vm2 <- new("VecchiaModel", n_neighbors = 10)
#' # fit separate scale parameters for location and elevation
#' soil.vm2 <- prestogp_fit(soil.vm2, y2, X2, locs2, scaling = c(1, 1, 2))
#'
#' pseq <- create_param_sequence(1, 2)
#' soil2.params <- soil.vm2@covparams
#' # sigma
#' soil2.params[pseq[1,1]:pseq[1,2]]
#' # scale parameters
#' soil2.params[pseq[2,1]:pseq[2,2]]
#' # smoothness parameter
#' soil2.params[pseq[3,1]:pseq[3,2]]
#' # nugget
#' soil2.params[pseq[4,1]:pseq[4,2]]
#'
#' # Multivariate model
#' ym <- list()
#' ym[[1]] <- soil250[,4] # predict sand/silt portion of the sample
#' ym[[2]] <- soil250[,5]
#' ym[[3]] <- soil250[,6]
#' Xm <- list()
#' Xm[[1]] <- Xm[[2]] <- Xm[[3]] <- as.matrix(soil250[,7:22])
#' locsm <- list()
#' locsm[[1]] <- locsm[[2]] <- locsm[[3]] <- as.matrix(soil250[,1:3])
#'
#' soil.mvm <-  new("MultivariateVecchiaModel", n_neighbors = 10)
#' soil.mvm <- prestogp_fit(soil.mvm, ym, Xm, locsm)
#'
#' pseq <- create_param_sequence(3, 2)
#' soil.params <- soil.mvm@covparams
#' # sigmas
#' soil.params[pseq[1,1]:pseq[1,2]]
#' # scale parameters
#' scale.seq <- pseq[2,1]:pseq[2,2]
#' # scale parameter for location, outcome 1
#' soil.params[scale.seq[1]]
#' # scale parameter for elevation, outcome 1
#' soil.params[scale.seq[2]]
#' # scale parameter for location, outcome 2
#' soil.params[scale.seq[3]]
#' # scale parameter for elevation, outcome 2
#' soil.params[scale.seq[4]]
#' # scale parameter for location, outcome 3
#' soil.params[scale.seq[5]]
#' # scale parameter for elevation, outcome 3
#' soil.params[scale.seq[6]]
#' # smoothness parameters
#' soil.params[pseq[3,1]:pseq[3,2]]
#' # nuggets
#' soil.params[pseq[4,1]:pseq[4,2]]
#' # correlation
#' soil.corr <- diag(2) / 2
#' soil.corr[upper.tri(soil.corr)] <- soil.params[pseq[5,1]:pseq[5,2]]
#' soil.corr <- soil.corr + t(soil.corr)
create_param_sequence <- function(P, ns = 1) {
    .Call('_PrestoGP_create_param_sequence', PACKAGE = 'PrestoGP', P, ns)
}

nearPD_cpp <- function(x, corr = FALSE, keepDiag = FALSE, do2eigen = TRUE, doSym = FALSE, doDykstra = TRUE, only_values = FALSE, eig_tol = 1e-6, conv_tol = 1e-7, posd_tol = 1e-8, maxit = 100L, trace = FALSE) {
    .Call('_PrestoGP_nearPD_cpp', PACKAGE = 'PrestoGP', x, corr, keepDiag, do2eigen, doSym, doDykstra, only_values, eig_tol, conv_tol, posd_tol, maxit, trace)
}

U2V_cpp <- function(U_obj) {
    .Call('_PrestoGP_U2V_cpp', PACKAGE = 'PrestoGP', U_obj)
}

