name: test-mkl-ubuntu-latest
on:
    push:
      branches:
        - intel-mkl-action
jobs:
    build:
      runs-on: ${{ matrix.config.os }}
      strategy:
        fail-fast: false
        matrix:
          config:
            - {os: ubuntu-latest,   r: 'release'}
      steps:
        - name: add oneAPI to apt
          shell: bash
          run: |
            cd /tmp
            wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
            sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
            rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
            sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
        - uses: awalsh128/cache-apt-pkgs-action@latest
          with: 
            packages: intel-mkl libmkl-dev
            version: 1.0
        - name: install oneAPI MKL library
          shell: bash
          run: |
            sudo apt install intel-mkl libmkl-dev
        - uses: r-lib/actions/setup-r@v2
          with:
            r-version: ${{ matrix.config.r }}
            http-user-agent: ${{ matrix.config.http-user-agent }}
            use-public-rspm: true
        - uses: r-lib/actions/setup-r-dependencies@v2
          with: 
            packages: |
                any::microbenchmark
        - name: check R performance
          shell: Rscript {0}
          run: |
            library(microbenchmark)
            microbenchmark(
              rnorm(1000000),
              times = 10000
            )
        - name: Link MKL
          shell: bash
          run: |
            update-alternatives --install /usr/lib/x86_64-linux-gnu/libblas.so     \
            libblas.so-x86_64-linux-gnu      /opt/intel/mkl/lib/intel64/libmkl_rt.so 50
            update-alternatives --install /usr/lib/x86_64-linux-gnu/libblas.so.3   \
            libblas.so.3-x86_64-linux-gnu    /opt/intel/mkl/lib/intel64/libmkl_rt.so 50
            update-alternatives --install /usr/lib/x86_64-linux-gnu/liblapack.so   \
            liblapack.so-x86_64-linux-gnu    /opt/intel/mkl/lib/intel64/libmkl_rt.so 50
            update-alternatives --install /usr/lib/x86_64-linux-gnu/liblapack.so.3 \
            liblapack.so.3-x86_64-linux-gnu  /opt/intel/mkl/lib/intel64/libmkl_rt.so 50
            echo "/opt/intel/lib/intel64"     >  /etc/ld.so.conf.d/mkl.conf
            echo "/opt/intel/mkl/lib/intel64" >> /etc/ld.so.conf.d/mkl.conf
            ldconfig
        - name: Check R sessionInfo
          shell: Rscript
          run: |
            sessionInfo()
        - name: check R performance after MKL
          shell: Rscript {0}
          run: |
            library(microbenchmark)
            microbenchmark(
              rnorm(1000000),
              times = 10000
            )